language: node_js
node_js:
    - "0.10"
    - "0.12"
    - 6
    - 8
    - 10
    - 11
env:
    - UGLIFYJS_TEST_ALL=1 TRAVIS=1
matrix:
  fast_finish: true
cache:
  directories:
    - tmp
    - node_modules
