language: node_js

os: linux

cache:
  directories:
    - node_modules

jobs:
  include:
    - name: Functional tests
      script: test/functional.sh
      node_js: 12
      cache:
        directories:
          - node_modules
          - terser-functional-tests

    - node_js: 12
      env:
        - TERSER_TEST_ALL=1
      cache:
        directories:
          - node_modules
          - tmp

    - node_js: 8

    - node_js: 12
      os: windows

